USE gmonstar_orchestration;
--
-- Updating data of table api
--
UPDATE api SET error_code_key = 'code', error_code_description = 'description' WHERE id = 66;
UPDATE api SET error_code_key = 'code', error_code_description = 'description' WHERE id = 128;

--
-- Updating data of table inherit_api_input_parameters
--
UPDATE inherit_api_input_parameters SET length = NULL WHERE id = 562;

--
-- Inserting data into table inherit_notification
--
INSERT INTO inherit_notification(id, api_api_group_id, notification_id) VALUES
(56, 139, 77),
(57, 216, 103),
(58, 218, 103);


--
-- Inserting data into table inherit_notification_template
--
INSERT INTO inherit_notification_template(id, template, inherit_notification_id, response_code, is_response, get_response_key, set_response_key, response_http_code) VALUES
(1002, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 7, 'CMN006', NULL, NULL, NULL, NULL),
(1003, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 7, 'CMN001', NULL, NULL, NULL, NULL),
(1004, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 7, 'CMN002', NULL, NULL, NULL, NULL),
(1005, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 7, 'CMN003', NULL, NULL, NULL, NULL),
(1006, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 7, 'CMN005', NULL, NULL, NULL, NULL),
(1007, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 56, 'CMN001', NULL, NULL, NULL, NULL),
(1008, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 56, 'CMN002', NULL, NULL, NULL, NULL),
(1009, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 56, 'CMN003', NULL, NULL, NULL, NULL),
(1010, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 56, 'CMN004', NULL, NULL, NULL, NULL),
(1011, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 56, 'CMN005', NULL, NULL, NULL, NULL),
(1012, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 56, 'CMN006', NULL, NULL, NULL, NULL),
(1013, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 57, 'CMN001', NULL, NULL, NULL, NULL),
(1014, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 57, 'CMN002', NULL, NULL, NULL, NULL),
(1015, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 57, 'CMN003', NULL, NULL, NULL, NULL),
(1016, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 57, 'CMN004', NULL, NULL, NULL, NULL),
(1017, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 57, 'CMN005', NULL, NULL, NULL, NULL),
(1018, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 57, 'CMN006', NULL, NULL, NULL, NULL),
(1019, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 58, 'CMN001', NULL, NULL, NULL, NULL),
(1020, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 58, 'CMN002', NULL, NULL, NULL, NULL),
(1021, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 58, 'CMN003', NULL, NULL, NULL, NULL),
(1022, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 58, 'CMN004', NULL, NULL, NULL, NULL),
(1023, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 58, 'CMN005', NULL, NULL, NULL, NULL),
(1024, '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''errors'': [{''code'':''CMN-INB002'', ''description'':''<description>''}],  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' }}"}]', 58, 'CMN006', NULL, NULL, NULL, NULL);



--
-- Updating data of table inherit_notification_template
--
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderCancelled","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''0'', ''description'':''Success''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<gmPlanId>'', ''orderId'':''<ids>'',''effectiveDate'':''<removalTimestamp>'',''instanceId'':''<instanceId>''},''refundDetails'': {''currency'': ''<currency>'',''refundAmount'': ''<refundAmount>'' }}"}]' WHERE id = 358;
