USE gmonstar_orchestration;
--
-- Updating data of table api
--
UPDATE api SET url = 'rout/getAvailableOffer', method_type_id = 3 WHERE id = 51;

--
-- Inserting data into table api_api_group
--

DELETE from inherit_api_input_parameters where id IN (5394,5395,5396,5397,5398,5399,5400,5401,5403);
DELETE FROM api_api_group where id IN (220);
DELETE FROM api_input_parameters where id IN (4561);
INSERT INTO api_api_group(id, api_group_id, api_id, api_template, sequence) VALUES
(220, 59, 51, '{"countryIsoCode":"<countryIsoCode>"}', NULL);

--
-- Updating data of table api_input_parameters
--
UPDATE api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 707;
UPDATE api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 710;

--
-- Inserting data into table api_input_parameters
--

INSERT INTO api_input_parameters(id, api_id, name, data_type, is_header, length, regex, regex_description, client_parameter, client_parameter_value, is_required, is_query, is_body, is_path, is_prefix, prefix_value, is_suffix, suffix_value) VALUES
(4561, 51, 'userIdentifier', 'string', 1, NULL, NULL, NULL, 'ban', NULL, 1, 0, 1, 0, 0, NULL, 0, NULL);

--
-- Updating data of table inherit_api_input_parameters
--
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 59;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 77;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 119;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 178;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 206;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 222;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 235;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 265;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 270;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 376;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 380;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 490;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 494;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 543;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 547;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 550;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 557;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 574;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 578;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 630;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 646;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 652;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 669;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 718;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 727;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 735;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 752;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 756;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 761;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 769;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 786;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 790;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 856;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 909;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 915;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 918;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 965;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 1009;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 1041;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4653;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4673;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4683;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4693;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4703;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4718;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4733;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4748;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4763;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4778;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4793;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4808;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4823;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4838;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4853;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4868;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4883;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 4898;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 5005;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 5132;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 5261;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 5324;
UPDATE inherit_api_input_parameters SET regex_description = 'Value should be < 41 characters' WHERE id = 5383;

--
-- Inserting data into table inherit_api_input_parameters
--

INSERT INTO inherit_api_input_parameters(id, api_api_group_id, api_input_parameters_id, data_type, is_header, length, regex, regex_description, client_parameter, client_parameter_value, inherit_api_response_parameter_id, is_required, is_query, is_body, is_path, is_prefix, prefix_value, is_suffix, suffix_value) VALUES
(5394, 220, 4561, 'string', 0, '<41', '[a-zA-Z0-9 ]+', 'Value should be < 41 characters', 'userIdentifier', NULL, NULL, 1, 0, 0, 0, 0, NULL, 0, NULL),
(5395, 220, 1146, 'string', 0, NULL, 'application/json', 'Value should be only application/json', 'Accept', NULL, NULL, 1, 0, 0, 0, 0, NULL, 0, NULL),
(5396, 220, 2095, 'string', 1, NULL, '^[^-s][a-zA-Z0-9_|s-]+$', 'Value should be string with no spaces', 'requestId', NULL, NULL, 1, 0, 1, 0, 0, NULL, 0, NULL),
(5397, 220, 2138, 'string', 1, NULL, '[a-zA-Z ]+', 'Value should be string with no spaces', NULL, 'a330225c-d0c8-11e9-9dc7-0050568138a0', NULL, 1, 0, 1, 0, 0, NULL, 0, NULL),
(5398, 220, 2181, 'string', 1, NULL, '[a-zA-Z ]+', 'Value should be string with no spaces', 'access_token', '7e96ca42-e0e7-11e9-8bee-fe984cc15272', NULL, 1, 0, 1, 0, 0, NULL, 0, NULL),
(5399, 220, 2224, 'string', 1, NULL, NULL, NULL, NULL, 'userIdentifier', NULL, 1, 0, 1, 0, 0, NULL, 0, NULL),
(5400, 220, 2267, 'string', 1, NULL, NULL, NULL, 'userIdentifier', NULL, NULL, 1, 0, 1, 0, 0, NULL, 0, NULL),
(5401, 220, 2310, 'string', 1, NULL, '[a-zA-Z ]+', 'Value should be string with no spaces', NULL, 'application/json;charset=UTF-8', NULL, 1, 0, 1, 0, 0, NULL, 0, NULL),
(5403, 220, 853, 'string', 0, NULL, NULL, 'Value should not contain special character', 'country', NULL, NULL, 1, 0, 0, 0, 0, NULL, 0, NULL);



--
-- Updating data of table inherit_notification_template
--
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [101]: [Invalid credentials]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 278;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [102]: [Invalid token]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 279;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [103]: [Expired token]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 280;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [104]: [Restricted operation]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 281;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [106]: [External party call was unsuccessful]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 282;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [109]: [Malformed request object]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 283;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''0'',''description'':''Success''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 284;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [300]: [There is no started session, please log in correctly]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 285;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [301]: [Session was stopeed, please log in]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 286;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [618]: [Invalid login data]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 288;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''ACC001'',''description'':''Invalid Parameter: [ParameterName] Value not supported''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 289;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''ACC001'',''description'':''Invalid Parameter: [ParameterName]  Value not supported''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 290;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [642]: [Entry was not found by provided  identifier]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 291;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [900]: [Access denied]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 292;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [901]: [Black listed user performed operation. Access denied]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 293;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [904]: [SLA conditions were not met]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 294;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [101]: [Invalid credentials]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 318;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [102]: [Invalid token]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 319;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [103]: [Expired token]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 320;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [104]: [Restricted operation]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 321;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [106]: [External party call was unsuccessful]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 322;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [109]: [Malformed request object]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 323;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''0'',''description'':''Success''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 324;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [300]: [There is no started session, please log in correctly]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 325;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [301]: [Session was stopeed, please log in]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 326;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [618]: [Invalid login data]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 328;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''ACC001'',''description'':''Invalid Parameter: [ParameterName]  Value not supported''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 329;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''ACC001'',''description'':''Invalid Parameter: [ParameterName]  Value not supported''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 330;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [642]: [Entry was not found by provided  identifier]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 331;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [900]: [Access denied]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 332;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [901]: [Black listed user performed operation. Access denied]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 333;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [904]: [SLA conditions were not met]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 334;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [101]: [Invalid credentials]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 393;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [102]: [Invalid token]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 394;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [103]: [Expired token]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 395;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [104]: [Restricted operation]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 396;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [106]: [External party call was unsuccessful]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 397;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [109]: [Malformed request object]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 398;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''0'',''description'':''Success''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 399;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [300]: [There is no started session, please log in correctly]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 400;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [301]: [Session was stopeed, please log in]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 401;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''ACC003'',''description'':''requestId or BAN may not be found in GM system''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 402;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [618]: [Invalid login data]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 403;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''ACC001'',''description'':''Invalid Parameter: [ParameterName]  Value not supported''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 404;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''ACC001'',''description'':''Invalid Parameter: [ParameterName]  Value not supported''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 405;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [642]: [Entry was not found by provided  identifier]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 406;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [900]: [Access denied]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 407;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [901]: [Black listed user performed operation. Access denied]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 408;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/accountClosed","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [904]: [SLA conditions were not met]''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 409;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1",com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [101]: [Invalid credentials]''} ,''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 410;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [102]: [Invalid token]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 411;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [103]: [Expired token]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 412;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [104]: [Restricted operation]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 413;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [106]: [External party call was unsuccessful]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 414;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [109]: [Malformed request object]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 415;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''0'',''description'':''Success''},''deviceDetails'': {''iccid'': ''<iccid>'',''imsi'': ''<imsi>'',''msisdn'': ''<msisdn>''}}"}]' WHERE id = 416;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [300]: [There is no started session, please log in correctly]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 417;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [301]: [Session was stopeed, please log in]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 418;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [618]: [Invalid login data]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 440;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''ACO001'',''description'':''Invalid Parameter: [ParameterName]  Value not supported''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 441;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''ACO001'',''description'':''Invalid Parameter: [ParameterName]  Value not supported''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 442;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [642]: [Entry was not found by provided  identifier]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 444;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [900]: [Access denied]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 445;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [901]: [Black listed user performed operation. Access denied]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 446;
UPDATE inherit_notification_template SET template = '[ {"notification_type":"webhook","api_url":"<returnUrl>/subscribers/events/accountCreated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1", "api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''ban'':''<userIdentifier>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [904]: [SLA conditions were not met]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 447;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [101]: [Invalid credentials]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 448;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [102]: [Invalid token]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 449;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [103]: [Expired token]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 450;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [104]: [Restricted operation]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 451;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [106]: [External party call was unsuccessful]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 452;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [109]: [Malformed request object]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 453;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''0'', ''description'':''Success''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 454;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [300]: [There is no started session, please log in correctly]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 455;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [301]: [Session was stopeed, please log in]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 456;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [505]: [User was not found by provided parameters]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 457;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [618]: [Invalid login data]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 458;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''ORA001'', ''description'':''Invalid Parameter: [ParameterName]  Value not supported''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 459;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''ORA001'', ''description'':''Invalid Parameter: [ParameterName]  Value not supported''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 460;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''ORA001'', ''description'':''Invalid Parameter: [ParameterName]  Value not supported''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 461;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [642]: [Entry was not found by provided  identifier]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 462;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''ORA003'', ''description'':''Data Not Found : [external extrapass]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 464;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [801]: [Required order parameters not provided]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 466;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [900]: [Access denied]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 468;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [901]: [Black listed user performed operation. Access denied]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 469;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<userIdentifier>/events/orderAdded","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":"{''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_goup_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestIdMsg>'',''eventStatus'': {''code'':''CMN-INB002'', ''description'':''Downstream System Error: [904]: [SLA conditions were not met]''},  ''deviceDetails'': {''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>'' },  ''orderDetails'': {''planId'':''<externalExtraPassId>'', ''orderId'':''<userPurchaseId>'',''effectiveDate'':''<created>'',''instanceId'':''1''      }}"}]' WHERE id = 470;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountUpdated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestId>'',''eventStatus'':{''code'':''CMN-INB003'',''description'':''Downstream System Unavailable: [Subscription Manager not available]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 624;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountUpdated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestId>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [ErrorCode:2]: [ Device Detail (eUICC ID /IMSI / ICCID / MSISDN) Not Found in Subscription Management Database]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 625;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountUpdated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestId>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [ErrorCode:3]: [ No Profile Found for the mentioned country in Subscription Management Database]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 626;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountUpdated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestId>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [ErrorCode:4]: [the mentioned country is not a valid country ]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 627;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountUpdated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestId>'',''eventStatus'':{''code'':''CMN-INB001'',''description'':''Execution Failed: [Internal Error Executing the operation]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 628;
UPDATE inherit_notification_template SET template = '[{"notification_type":"webhook","api_url":"<returnUrl>/subscribers/<ban>/events/accountUpdated","method_type":"POST","notification_id":"@tracking_message_header","table_name":"","table_parameter":"","header_parameter":" {''Authorization'':''Basic SmVyc2V5IFRlbGVjb206T25zdGFyITUw''}","db_driver":"com.mysql.jdbc.Driver","api_type":"REST","db_url":"","end_node_name":"true","end_node_ip":"127.0.0.1","api_group_id":"@api_group_id","api_id":"@api_id","body_parameter":"{''requestId'':''<requestId>'',''eventStatus'':{''code'':''CMN-INB002'',''description'':''Downstream System Error: [ErrorCode:6]: [Operation was already performed in the Device]''},''deviceDetails'':{''iccid'':''<iccid>'',''imsi'':''<imsi>'',''msisdn'':''<msisdn>''}}"}]' WHERE id = 629;
